version: '3.8'

services:
  tokokita_expressjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9182:5151
    depends_on:
      - tokokita_db
      - tokokita_migration
    env_file:
      - .env.production
    volumes:
      - tokokita_volume:/app/node_modules
      - .:/app

  tokokita_migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - tokokita_db
    env_file:
      - .env.production
    command: sh -c "npm run db:migrate:prod && npm run db:seed:prod"
    restart: on-failure

  tokokita_db:
    image: postgres:14
    ports:
      - 5437:5432
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=tokokita

volumes:
  tokokita_volume:
